### ISSUE TITLE
SessionNotCreatedException

### ISSUE THREAD

**Issue by bklaus002** [umihico/selenium-lambda-layer#2]
Many thanks for making this lambda-layer available through Github! 

I uploaded the layer.zip file manually via S3 as the executing row 9 in your `publish_selenium_layer.sh` file returned an error since the file was larger than 50MB.

Then I modified the lambda function slightly (see below):

from selenium import webdriver
import json

def Chrome():
    options = webdriver.ChromeOptions()
    options.binary_location = "/opt/python/bin/headless-chromium"
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--window-size=1280x1696")
    options.add_argument("--disable-application-cache")
    options.add_argument("--disable-infobars")
    options.add_argument("--no-sandbox")
    options.add_argument("--hide-scrollbars")
    options.add_argument("--enable-logging")
    options.add_argument("--log-level=0")
    options.add_argument("--single-process")
    options.add_argument("--ignore-certificate-errors")
    options.add_argument("--homedir=/tmp")
    chrome = webdriver.Chrome(
        "/opt/python/bin/chromedriver", chrome_options=options)
    return chrome

def lambda_handler(event, context):
    chrome = Chrome()
    chrome.get('https://google.com')
    title = chrome.title
    chrome.quit()
    return {
        'statusCode': 200,
        'body': json.dumps(title)
    }

But when testing it in AWS it returned this error message. Do you have any suggestions?

Response
{
  "errorMessage": "Message: session not created exception: Missing or invalid capabilities\n  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.14.255-273-220.498.amzn2.x86_64 x86_64)\n",
  "errorType": "SessionNotCreatedException",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 25, in lambda_handler\n    chrome = Chrome()\n",
    "  File \"/var/task/lambda_function.py\", line 20, in Chrome\n    \"/opt/python/bin/chromedriver\", chrome_options=options)\n",
    "  File \"/opt/python/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    service_log_path, service, keep_alive)\n",
    "  File \"/opt/python/selenium/webdriver/chromium/webdriver.py\", line 98, in __init__\n    options=options)\n",
    "  File \"/opt/python/selenium/webdriver/remote/webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n",
    "  File \"/opt/python/selenium/webdriver/remote/webdriver.py\", line 365, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n",
    "  File \"/opt/python/selenium/webdriver/remote/webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n",
    "  File \"/opt/python/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"
  ]
}

Function Logs
START RequestId: fda16e02-27d4-49ef-819a-5dcfd5c18cc6 Version: $LATEST
[ERROR] SessionNotCreatedException: Message: session not created exception: Missing or invalid capabilities
(Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.14.255-273-220.498.amzn2.x86_64 x86_64)
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 25, in lambda_handler
    chrome = Chrome()
  File "/var/task/lambda_function.py", line 20, in Chrome
    "/opt/python/bin/chromedriver", chrome_options=options)
  File "/opt/python/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/opt/python/selenium/webdriver/chromium/webdriver.py", line 98, in __init__
    options=options)
  File "/opt/python/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/python/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/python/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/opt/python/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)

**Comment by umihico** [comment]
You successfully uploaded after your modification? why mine exceeded 50MB and your modification make it smaller? how?

**Comment by umihico** [comment]
and please consider to use docker image lambda layer is older feature

**Comment by bklaus002** [comment]
> You successfully uploaded after your modification? why mine exceeded 50MB and your modification make it smaller? how?

Running your sh-file (i.e. row 9) results in an error as your ZIP-file is >50MB. Hence, one cannot upload it via CLI, but it needs to be uploaded to an S3 before. Maybe you want to change your sh-file and mentioned it to the users.

**Comment by bklaus002** [comment]
> and please consider to use docker image lambda layer is older feature

And at the end, as I shared with my error messages, the configuration of Selenium and/or Chrome produces an error too, so it is not working as intended.
